# Generated by Django 6.0 on 2026-03-29 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchedentry',
            name='genre_ids',
            field=models.JSONField(default=list),
        ),
    ]
