# Generated by Django 6.0 on 2026-04-19 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0003_tmdbprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='TMDBMediaCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_id', models.IntegerField()),
                ('media_type', models.CharField(max_length=10)),
                ('genre_ids', models.JSONField(default=list)),
                ('top_cast', models.JSONField(default=list)),
                ('cached_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('media_id', 'media_type')},
            },
        ),
    ]
