# Generated by Django 6.0 on 2026-05-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0006_followedperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchedentry',
            name='original_language',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='watchedentry',
            name='release_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
