# Generated by Django 4.2.30 on 2026-05-29 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0008_add_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='episodeprogress',
            name='episode_user_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='followedperson',
            name='followed_user_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='ratingentry',
            name='rating_user_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='watchedentry',
            name='watched_user_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='watchedentry',
            name='watched_user_year_idx',
        ),
        migrations.RemoveIndex(
            model_name='watchlistentry',
            name='watchlist_user_date_idx',
        ),
    ]
