# Generated by Django 6.0 on 2026-05-30 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0009_remove_episodeprogress_episode_user_date_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRecommendationCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_you_json', models.JSONField(default=list)),
                ('personalized_json', models.JSONField(default=list)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rec_cache', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
