# Generated by Django 6.0.6 on 2026-07-03 16:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0010_userrecommendationcache'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingentry',
            name='user_rating',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
