# Generated by Django 6.0.6 on 2026-07-03 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0011_alter_ratingentry_user_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchedentry',
            name='watched_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
