# Generated by Django 6.0.6 on 2026-07-09 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0012_alter_watchedentry_watched_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchedentry',
            name='platform',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='watchedentry',
            name='runtime_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
