# Generated by Django 6.0.6 on 2026-07-10 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0014_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlistentry',
            name='watched',
        ),
    ]
