# Generated by Django 6.0.6 on 2026-07-11 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0015_remove_watchlistentry_watched'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlistitem',
            name='watched',
        ),
    ]
