# Generated by Django 5.2.17 on 2026-10-05 11:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userdata", "0018_cleanup_unsafe_avatar_extensions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ratingentry",
            name="rated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="watchedentry",
            name="watched_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="watchlistentry",
            name="added_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
