# Generated by Django 5.2.17 on 2026-10-07 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userdata", "0019_bulk_import_timestamps"),
    ]

    operations = [
        migrations.AddField(
            model_name="watchedentry",
            name="watched_tz",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
