# Generated by Django 5.2.17 on 2026-10-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userdata", "0020_watchedentry_watched_tz"),
    ]

    operations = [
        migrations.AddField(
            model_name="userrecommendationcache",
            name="refreshing_since",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
