# Generated by Django 5.2.17 on 2026-10-09 06:12

from django.db import migrations, models


def settle_not_found_rows(apps, schema_editor):
    # Rows the backfill's 404 path already wrote (the sentinels in
    # metadata_backfill.py). Other genre-less rows can't be told apart from an
    # import that supplied language/year, so they're fetched once more and settle then.
    WatchedEntry = apps.get_model("userdata", "WatchedEntry")
    WatchedEntry.objects.filter(genre_ids=[], original_language="??", release_year=-1).update(
        metadata_settled=True
    )


class Migration(migrations.Migration):

    dependencies = [
        ("userdata", "0021_userrecommendationcache_refreshing_since"),
    ]

    operations = [
        migrations.AddField(
            model_name="watchedentry",
            name="metadata_settled",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(settle_not_found_rows, migrations.RunPython.noop),
    ]
