import re
from pathlib import Path

import django
from django.test import SimpleTestCase

REQUIREMENTS = Path(__file__).resolve().parents[2] / "requirements.txt"


class DjangoVersionTests(SimpleTestCase):
    def test_django_version_matches_requirements(self):
        """Catches running manage.py/pytest with the wrong interpreter (base
        Anaconda has Django 6.0, which is how migrations ended up saying
        "Generated by Django 6.0"). Major.minor only, so patch bumps don't
        need this test touched."""
        match = re.search(r"^Django==(\d+)\.(\d+)", REQUIREMENTS.read_text(encoding="utf-8"), re.M | re.I)
        self.assertIsNotNone(match, f"no `Django==X.Y.Z` pin in {REQUIREMENTS}")
        pinned = (int(match.group(1)), int(match.group(2)))
        self.assertEqual(
            django.VERSION[:2],
            pinned,
            f"Installed Django {django.get_version()} doesn't match the {pinned[0]}.{pinned[1]} pin in "
            f"requirements.txt. Wrong interpreter? Use the project env (see CLAUDE.md).",
        )
