import re
from importlib.metadata import PackageNotFoundError, version
from pathlib import Path

import django
from django.test import SimpleTestCase

REQUIREMENTS = Path(__file__).resolve().parents[2] / "requirements.txt"
TEST_REQUIREMENTS = REQUIREMENTS.with_name("requirements-test.txt")
CONSTRAINTS = REQUIREMENTS.with_name("constraints.txt")


class RuffVersionTests(SimpleTestCase):
    def _pin(self, path):
        match = re.search(r"^ruff==(\S+)", path.read_text(encoding="utf-8"), re.M)
        self.assertIsNotNone(match, f"no `ruff==X.Y.Z` pin in {path}")
        return match.group(1)

    def test_installed_ruff_matches_pin(self):
        """CI lints with the pinned ruff; a local ruff that differs can pass
        code CI rejects (or the other way round)."""
        pinned = self._pin(TEST_REQUIREMENTS)
        self.assertEqual(self._pin(CONSTRAINTS), pinned, "constraints.txt and requirements-test.txt disagree on ruff")
        try:
            installed = version("ruff")
        except PackageNotFoundError:
            self.fail(f"ruff isn't installed; pip install -r requirements-test.txt -c constraints.txt (pin {pinned})")
        self.assertEqual(installed, pinned, f"Installed ruff {installed} doesn't match the {pinned} pin")


class DjangoVersionTests(SimpleTestCase):
    def test_django_version_matches_requirements(self):
        """Catches running manage.py/pytest with the wrong interpreter (base
        Anaconda has Django 6.0, which is how migrations ended up saying
        "Generated by Django 6.0"). Major.minor only, so patch bumps don't
        need this test touched."""
        match = re.search(r"^Django==(\d+)\.(\d+)", REQUIREMENTS.read_text(encoding="utf-8"), re.M | re.I)
        self.assertIsNotNone(match, f"no `Django==X.Y.Z` pin in {REQUIREMENTS}")
        pinned = (int(match.group(1)), int(match.group(2)))
        self.assertEqual(
            django.VERSION[:2],
            pinned,
            f"Installed Django {django.get_version()} doesn't match the {pinned[0]}.{pinned[1]} pin in "
            f"requirements.txt. Wrong interpreter? Use the project env (see CLAUDE.md).",
        )
